/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSoporteRouteImport } from './routes/_app/soporte'
import { Route as AppReservasRouteImport } from './routes/_app/reservas'
import { Route as AppPerfilRouteImport } from './routes/_app/perfil'
import { Route as AppNotificacionesRouteImport } from './routes/_app/notificaciones'
import { Route as AppMisVehiculosRouteImport } from './routes/_app/mis-vehiculos'
import { Route as AppMisReservasRouteImport } from './routes/_app/mis-reservas'
import { Route as AppFavoritosRouteImport } from './routes/_app/favoritos'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppBuscarRouteImport } from './routes/_app/buscar'
import { Route as AppVehiculosIdRouteImport } from './routes/_app/vehiculos.$id'
import { Route as AppReservasIdRouteImport } from './routes/_app/reservas.$id'
import { Route as AppMisVehiculosNuevoRouteImport } from './routes/_app/mis-vehiculos.nuevo'
import { Route as AppMisReservasIdRouteImport } from './routes/_app/mis-reservas.$id'

const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSoporteRoute = AppSoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => AppRoute,
} as any)
const AppReservasRoute = AppReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacionesRoute = AppNotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppMisVehiculosRoute = AppMisVehiculosRouteImport.update({
  id: '/mis-vehiculos',
  path: '/mis-vehiculos',
  getParentRoute: () => AppRoute,
} as any)
const AppMisReservasRoute = AppMisReservasRouteImport.update({
  id: '/mis-reservas',
  path: '/mis-reservas',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritosRoute = AppFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBuscarRoute = AppBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => AppRoute,
} as any)
const AppVehiculosIdRoute = AppVehiculosIdRouteImport.update({
  id: '/vehiculos/$id',
  path: '/vehiculos/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReservasIdRoute = AppReservasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppReservasRoute,
} as any)
const AppMisVehiculosNuevoRoute = AppMisVehiculosNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => AppMisVehiculosRoute,
} as any)
const AppMisReservasIdRoute = AppMisReservasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMisReservasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/buscar': typeof AppBuscarRoute
  '/dashboard': typeof AppDashboardRoute
  '/favoritos': typeof AppFavoritosRoute
  '/mis-reservas': typeof AppMisReservasRouteWithChildren
  '/mis-vehiculos': typeof AppMisVehiculosRouteWithChildren
  '/notificaciones': typeof AppNotificacionesRoute
  '/perfil': typeof AppPerfilRoute
  '/reservas': typeof AppReservasRouteWithChildren
  '/soporte': typeof AppSoporteRoute
  '/mis-reservas/$id': typeof AppMisReservasIdRoute
  '/mis-vehiculos/nuevo': typeof AppMisVehiculosNuevoRoute
  '/reservas/$id': typeof AppReservasIdRoute
  '/vehiculos/$id': typeof AppVehiculosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/buscar': typeof AppBuscarRoute
  '/dashboard': typeof AppDashboardRoute
  '/favoritos': typeof AppFavoritosRoute
  '/mis-reservas': typeof AppMisReservasRouteWithChildren
  '/mis-vehiculos': typeof AppMisVehiculosRouteWithChildren
  '/notificaciones': typeof AppNotificacionesRoute
  '/perfil': typeof AppPerfilRoute
  '/reservas': typeof AppReservasRouteWithChildren
  '/soporte': typeof AppSoporteRoute
  '/mis-reservas/$id': typeof AppMisReservasIdRoute
  '/mis-vehiculos/nuevo': typeof AppMisVehiculosNuevoRoute
  '/reservas/$id': typeof AppReservasIdRoute
  '/vehiculos/$id': typeof AppVehiculosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/_app/buscar': typeof AppBuscarRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/favoritos': typeof AppFavoritosRoute
  '/_app/mis-reservas': typeof AppMisReservasRouteWithChildren
  '/_app/mis-vehiculos': typeof AppMisVehiculosRouteWithChildren
  '/_app/notificaciones': typeof AppNotificacionesRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/reservas': typeof AppReservasRouteWithChildren
  '/_app/soporte': typeof AppSoporteRoute
  '/_app/mis-reservas/$id': typeof AppMisReservasIdRoute
  '/_app/mis-vehiculos/nuevo': typeof AppMisVehiculosNuevoRoute
  '/_app/reservas/$id': typeof AppReservasIdRoute
  '/_app/vehiculos/$id': typeof AppVehiculosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recuperar'
    | '/registro'
    | '/buscar'
    | '/dashboard'
    | '/favoritos'
    | '/mis-reservas'
    | '/mis-vehiculos'
    | '/notificaciones'
    | '/perfil'
    | '/reservas'
    | '/soporte'
    | '/mis-reservas/$id'
    | '/mis-vehiculos/nuevo'
    | '/reservas/$id'
    | '/vehiculos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recuperar'
    | '/registro'
    | '/buscar'
    | '/dashboard'
    | '/favoritos'
    | '/mis-reservas'
    | '/mis-vehiculos'
    | '/notificaciones'
    | '/perfil'
    | '/reservas'
    | '/soporte'
    | '/mis-reservas/$id'
    | '/mis-vehiculos/nuevo'
    | '/reservas/$id'
    | '/vehiculos/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/recuperar'
    | '/registro'
    | '/_app/buscar'
    | '/_app/dashboard'
    | '/_app/favoritos'
    | '/_app/mis-reservas'
    | '/_app/mis-vehiculos'
    | '/_app/notificaciones'
    | '/_app/perfil'
    | '/_app/reservas'
    | '/_app/soporte'
    | '/_app/mis-reservas/$id'
    | '/_app/mis-vehiculos/nuevo'
    | '/_app/reservas/$id'
    | '/_app/vehiculos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecuperarRoute: typeof RecuperarRoute
  RegistroRoute: typeof RegistroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/soporte': {
      id: '/_app/soporte'
      path: '/soporte'
      fullPath: '/soporte'
      preLoaderRoute: typeof AppSoporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservas': {
      id: '/_app/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof AppReservasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notificaciones': {
      id: '/_app/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof AppNotificacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mis-vehiculos': {
      id: '/_app/mis-vehiculos'
      path: '/mis-vehiculos'
      fullPath: '/mis-vehiculos'
      preLoaderRoute: typeof AppMisVehiculosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mis-reservas': {
      id: '/_app/mis-reservas'
      path: '/mis-reservas'
      fullPath: '/mis-reservas'
      preLoaderRoute: typeof AppMisReservasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favoritos': {
      id: '/_app/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AppFavoritosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buscar': {
      id: '/_app/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof AppBuscarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vehiculos/$id': {
      id: '/_app/vehiculos/$id'
      path: '/vehiculos/$id'
      fullPath: '/vehiculos/$id'
      preLoaderRoute: typeof AppVehiculosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservas/$id': {
      id: '/_app/reservas/$id'
      path: '/$id'
      fullPath: '/reservas/$id'
      preLoaderRoute: typeof AppReservasIdRouteImport
      parentRoute: typeof AppReservasRoute
    }
    '/_app/mis-vehiculos/nuevo': {
      id: '/_app/mis-vehiculos/nuevo'
      path: '/nuevo'
      fullPath: '/mis-vehiculos/nuevo'
      preLoaderRoute: typeof AppMisVehiculosNuevoRouteImport
      parentRoute: typeof AppMisVehiculosRoute
    }
    '/_app/mis-reservas/$id': {
      id: '/_app/mis-reservas/$id'
      path: '/$id'
      fullPath: '/mis-reservas/$id'
      preLoaderRoute: typeof AppMisReservasIdRouteImport
      parentRoute: typeof AppMisReservasRoute
    }
  }
}

interface AppMisReservasRouteChildren {
  AppMisReservasIdRoute: typeof AppMisReservasIdRoute
}

const AppMisReservasRouteChildren: AppMisReservasRouteChildren = {
  AppMisReservasIdRoute: AppMisReservasIdRoute,
}

const AppMisReservasRouteWithChildren = AppMisReservasRoute._addFileChildren(
  AppMisReservasRouteChildren,
)

interface AppMisVehiculosRouteChildren {
  AppMisVehiculosNuevoRoute: typeof AppMisVehiculosNuevoRoute
}

const AppMisVehiculosRouteChildren: AppMisVehiculosRouteChildren = {
  AppMisVehiculosNuevoRoute: AppMisVehiculosNuevoRoute,
}

const AppMisVehiculosRouteWithChildren = AppMisVehiculosRoute._addFileChildren(
  AppMisVehiculosRouteChildren,
)

interface AppReservasRouteChildren {
  AppReservasIdRoute: typeof AppReservasIdRoute
}

const AppReservasRouteChildren: AppReservasRouteChildren = {
  AppReservasIdRoute: AppReservasIdRoute,
}

const AppReservasRouteWithChildren = AppReservasRoute._addFileChildren(
  AppReservasRouteChildren,
)

interface AppRouteChildren {
  AppBuscarRoute: typeof AppBuscarRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFavoritosRoute: typeof AppFavoritosRoute
  AppMisReservasRoute: typeof AppMisReservasRouteWithChildren
  AppMisVehiculosRoute: typeof AppMisVehiculosRouteWithChildren
  AppNotificacionesRoute: typeof AppNotificacionesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppReservasRoute: typeof AppReservasRouteWithChildren
  AppSoporteRoute: typeof AppSoporteRoute
  AppVehiculosIdRoute: typeof AppVehiculosIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBuscarRoute: AppBuscarRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFavoritosRoute: AppFavoritosRoute,
  AppMisReservasRoute: AppMisReservasRouteWithChildren,
  AppMisVehiculosRoute: AppMisVehiculosRouteWithChildren,
  AppNotificacionesRoute: AppNotificacionesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppReservasRoute: AppReservasRouteWithChildren,
  AppSoporteRoute: AppSoporteRoute,
  AppVehiculosIdRoute: AppVehiculosIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RecuperarRoute: RecuperarRoute,
  RegistroRoute: RegistroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
