/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificarRouteImport } from './routes/verificar'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSoporteRouteImport } from './routes/_app/soporte'
import { Route as AppReservasRouteImport } from './routes/_app/reservas'
import { Route as AppPerfilRouteImport } from './routes/_app/perfil'
import { Route as AppNotificacionesRouteImport } from './routes/_app/notificaciones'
import { Route as AppMisVehiculosRouteImport } from './routes/_app/mis-vehiculos'
import { Route as AppMapaRouteImport } from './routes/_app/mapa'
import { Route as AppLicenciaRouteImport } from './routes/_app/licencia'
import { Route as AppIdentidadRouteImport } from './routes/_app/identidad'
import { Route as AppFavoritosRouteImport } from './routes/_app/favoritos'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppConfiguracionRouteImport } from './routes/_app/configuracion'
import { Route as AppBuscarRouteImport } from './routes/_app/buscar'
import { Route as VoucherVerifyTokenRouteImport } from './routes/voucher.verify.$token'
import { Route as VoucherReturnTokenRouteImport } from './routes/voucher.return.$token'
import { Route as AppVehiculosIdRouteImport } from './routes/_app/vehiculos.$id'
import { Route as AppReservasIdRouteImport } from './routes/_app/reservas_.$id'
import { Route as AppReservasTransferenciaIdRouteImport } from './routes/_app/reservas-transferencia.$id'
import { Route as AppPerfilMediosDePagoRouteImport } from './routes/_app/perfil_.medios-de-pago'
import { Route as AppPerfilDatosRouteImport } from './routes/_app/perfil_.datos'
import { Route as AppPerfilCuentasRouteImport } from './routes/_app/perfil_.cuentas'
import { Route as AppPerfilIdRouteImport } from './routes/_app/perfil_.$id'
import { Route as AppMisVehiculosNuevoRouteImport } from './routes/_app/mis-vehiculos.nuevo'
import { Route as AppMisVehiculosIdRouteImport } from './routes/_app/mis-vehiculos.$id'
import { Route as AppVehiculosIdReservarRouteImport } from './routes/_app/vehiculos.$id_.reservar'
import { Route as AppReservasIdPagoRouteImport } from './routes/_app/reservas.$id.pago'
import { Route as AppMisVehiculosIdDocumentosRouteImport } from './routes/_app/mis-vehiculos.$id_.documentos'

const VerificarRoute = VerificarRouteImport.update({
  id: '/verificar',
  path: '/verificar',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSoporteRoute = AppSoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => AppRoute,
} as any)
const AppReservasRoute = AppReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacionesRoute = AppNotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppMisVehiculosRoute = AppMisVehiculosRouteImport.update({
  id: '/mis-vehiculos',
  path: '/mis-vehiculos',
  getParentRoute: () => AppRoute,
} as any)
const AppMapaRoute = AppMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AppRoute,
} as any)
const AppLicenciaRoute = AppLicenciaRouteImport.update({
  id: '/licencia',
  path: '/licencia',
  getParentRoute: () => AppRoute,
} as any)
const AppIdentidadRoute = AppIdentidadRouteImport.update({
  id: '/identidad',
  path: '/identidad',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritosRoute = AppFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionRoute = AppConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AppRoute,
} as any)
const AppBuscarRoute = AppBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => AppRoute,
} as any)
const VoucherVerifyTokenRoute = VoucherVerifyTokenRouteImport.update({
  id: '/voucher/verify/$token',
  path: '/voucher/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const VoucherReturnTokenRoute = VoucherReturnTokenRouteImport.update({
  id: '/voucher/return/$token',
  path: '/voucher/return/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVehiculosIdRoute = AppVehiculosIdRouteImport.update({
  id: '/vehiculos/$id',
  path: '/vehiculos/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReservasIdRoute = AppReservasIdRouteImport.update({
  id: '/reservas_/$id',
  path: '/reservas/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReservasTransferenciaIdRoute =
  AppReservasTransferenciaIdRouteImport.update({
    id: '/reservas-transferencia/$id',
    path: '/reservas-transferencia/$id',
    getParentRoute: () => AppRoute,
  } as any)
const AppPerfilMediosDePagoRoute = AppPerfilMediosDePagoRouteImport.update({
  id: '/perfil_/medios-de-pago',
  path: '/perfil/medios-de-pago',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilDatosRoute = AppPerfilDatosRouteImport.update({
  id: '/perfil_/datos',
  path: '/perfil/datos',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilCuentasRoute = AppPerfilCuentasRouteImport.update({
  id: '/perfil_/cuentas',
  path: '/perfil/cuentas',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilIdRoute = AppPerfilIdRouteImport.update({
  id: '/perfil_/$id',
  path: '/perfil/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMisVehiculosNuevoRoute = AppMisVehiculosNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => AppMisVehiculosRoute,
} as any)
const AppMisVehiculosIdRoute = AppMisVehiculosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMisVehiculosRoute,
} as any)
const AppVehiculosIdReservarRoute = AppVehiculosIdReservarRouteImport.update({
  id: '/vehiculos/$id_/reservar',
  path: '/vehiculos/$id/reservar',
  getParentRoute: () => AppRoute,
} as any)
const AppReservasIdPagoRoute = AppReservasIdPagoRouteImport.update({
  id: '/$id/pago',
  path: '/$id/pago',
  getParentRoute: () => AppReservasRoute,
} as any)
const AppMisVehiculosIdDocumentosRoute =
  AppMisVehiculosIdDocumentosRouteImport.update({
    id: '/$id_/documentos',
    path: '/$id/documentos',
    getParentRoute: () => AppMisVehiculosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/verificar': typeof VerificarRoute
  '/buscar': typeof AppBuscarRoute
  '/configuracion': typeof AppConfiguracionRoute
  '/dashboard': typeof AppDashboardRoute
  '/favoritos': typeof AppFavoritosRoute
  '/identidad': typeof AppIdentidadRoute
  '/licencia': typeof AppLicenciaRoute
  '/mapa': typeof AppMapaRoute
  '/mis-vehiculos': typeof AppMisVehiculosRouteWithChildren
  '/notificaciones': typeof AppNotificacionesRoute
  '/perfil': typeof AppPerfilRoute
  '/reservas': typeof AppReservasRouteWithChildren
  '/soporte': typeof AppSoporteRoute
  '/mis-vehiculos/$id': typeof AppMisVehiculosIdRoute
  '/mis-vehiculos/nuevo': typeof AppMisVehiculosNuevoRoute
  '/perfil/$id': typeof AppPerfilIdRoute
  '/perfil/cuentas': typeof AppPerfilCuentasRoute
  '/perfil/datos': typeof AppPerfilDatosRoute
  '/perfil/medios-de-pago': typeof AppPerfilMediosDePagoRoute
  '/reservas-transferencia/$id': typeof AppReservasTransferenciaIdRoute
  '/reservas/$id': typeof AppReservasIdRoute
  '/vehiculos/$id': typeof AppVehiculosIdRoute
  '/voucher/return/$token': typeof VoucherReturnTokenRoute
  '/voucher/verify/$token': typeof VoucherVerifyTokenRoute
  '/mis-vehiculos/$id/documentos': typeof AppMisVehiculosIdDocumentosRoute
  '/reservas/$id/pago': typeof AppReservasIdPagoRoute
  '/vehiculos/$id/reservar': typeof AppVehiculosIdReservarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/verificar': typeof VerificarRoute
  '/buscar': typeof AppBuscarRoute
  '/configuracion': typeof AppConfiguracionRoute
  '/dashboard': typeof AppDashboardRoute
  '/favoritos': typeof AppFavoritosRoute
  '/identidad': typeof AppIdentidadRoute
  '/licencia': typeof AppLicenciaRoute
  '/mapa': typeof AppMapaRoute
  '/mis-vehiculos': typeof AppMisVehiculosRouteWithChildren
  '/notificaciones': typeof AppNotificacionesRoute
  '/perfil': typeof AppPerfilRoute
  '/reservas': typeof AppReservasRouteWithChildren
  '/soporte': typeof AppSoporteRoute
  '/mis-vehiculos/$id': typeof AppMisVehiculosIdRoute
  '/mis-vehiculos/nuevo': typeof AppMisVehiculosNuevoRoute
  '/perfil/$id': typeof AppPerfilIdRoute
  '/perfil/cuentas': typeof AppPerfilCuentasRoute
  '/perfil/datos': typeof AppPerfilDatosRoute
  '/perfil/medios-de-pago': typeof AppPerfilMediosDePagoRoute
  '/reservas-transferencia/$id': typeof AppReservasTransferenciaIdRoute
  '/reservas/$id': typeof AppReservasIdRoute
  '/vehiculos/$id': typeof AppVehiculosIdRoute
  '/voucher/return/$token': typeof VoucherReturnTokenRoute
  '/voucher/verify/$token': typeof VoucherVerifyTokenRoute
  '/mis-vehiculos/$id/documentos': typeof AppMisVehiculosIdDocumentosRoute
  '/reservas/$id/pago': typeof AppReservasIdPagoRoute
  '/vehiculos/$id/reservar': typeof AppVehiculosIdReservarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/verificar': typeof VerificarRoute
  '/_app/buscar': typeof AppBuscarRoute
  '/_app/configuracion': typeof AppConfiguracionRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/favoritos': typeof AppFavoritosRoute
  '/_app/identidad': typeof AppIdentidadRoute
  '/_app/licencia': typeof AppLicenciaRoute
  '/_app/mapa': typeof AppMapaRoute
  '/_app/mis-vehiculos': typeof AppMisVehiculosRouteWithChildren
  '/_app/notificaciones': typeof AppNotificacionesRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/reservas': typeof AppReservasRouteWithChildren
  '/_app/soporte': typeof AppSoporteRoute
  '/_app/mis-vehiculos/$id': typeof AppMisVehiculosIdRoute
  '/_app/mis-vehiculos/nuevo': typeof AppMisVehiculosNuevoRoute
  '/_app/perfil_/$id': typeof AppPerfilIdRoute
  '/_app/perfil_/cuentas': typeof AppPerfilCuentasRoute
  '/_app/perfil_/datos': typeof AppPerfilDatosRoute
  '/_app/perfil_/medios-de-pago': typeof AppPerfilMediosDePagoRoute
  '/_app/reservas-transferencia/$id': typeof AppReservasTransferenciaIdRoute
  '/_app/reservas_/$id': typeof AppReservasIdRoute
  '/_app/vehiculos/$id': typeof AppVehiculosIdRoute
  '/voucher/return/$token': typeof VoucherReturnTokenRoute
  '/voucher/verify/$token': typeof VoucherVerifyTokenRoute
  '/_app/mis-vehiculos/$id_/documentos': typeof AppMisVehiculosIdDocumentosRoute
  '/_app/reservas/$id/pago': typeof AppReservasIdPagoRoute
  '/_app/vehiculos/$id_/reservar': typeof AppVehiculosIdReservarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recuperar'
    | '/registro'
    | '/verificar'
    | '/buscar'
    | '/configuracion'
    | '/dashboard'
    | '/favoritos'
    | '/identidad'
    | '/licencia'
    | '/mapa'
    | '/mis-vehiculos'
    | '/notificaciones'
    | '/perfil'
    | '/reservas'
    | '/soporte'
    | '/mis-vehiculos/$id'
    | '/mis-vehiculos/nuevo'
    | '/perfil/$id'
    | '/perfil/cuentas'
    | '/perfil/datos'
    | '/perfil/medios-de-pago'
    | '/reservas-transferencia/$id'
    | '/reservas/$id'
    | '/vehiculos/$id'
    | '/voucher/return/$token'
    | '/voucher/verify/$token'
    | '/mis-vehiculos/$id/documentos'
    | '/reservas/$id/pago'
    | '/vehiculos/$id/reservar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recuperar'
    | '/registro'
    | '/verificar'
    | '/buscar'
    | '/configuracion'
    | '/dashboard'
    | '/favoritos'
    | '/identidad'
    | '/licencia'
    | '/mapa'
    | '/mis-vehiculos'
    | '/notificaciones'
    | '/perfil'
    | '/reservas'
    | '/soporte'
    | '/mis-vehiculos/$id'
    | '/mis-vehiculos/nuevo'
    | '/perfil/$id'
    | '/perfil/cuentas'
    | '/perfil/datos'
    | '/perfil/medios-de-pago'
    | '/reservas-transferencia/$id'
    | '/reservas/$id'
    | '/vehiculos/$id'
    | '/voucher/return/$token'
    | '/voucher/verify/$token'
    | '/mis-vehiculos/$id/documentos'
    | '/reservas/$id/pago'
    | '/vehiculos/$id/reservar'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/recuperar'
    | '/registro'
    | '/verificar'
    | '/_app/buscar'
    | '/_app/configuracion'
    | '/_app/dashboard'
    | '/_app/favoritos'
    | '/_app/identidad'
    | '/_app/licencia'
    | '/_app/mapa'
    | '/_app/mis-vehiculos'
    | '/_app/notificaciones'
    | '/_app/perfil'
    | '/_app/reservas'
    | '/_app/soporte'
    | '/_app/mis-vehiculos/$id'
    | '/_app/mis-vehiculos/nuevo'
    | '/_app/perfil_/$id'
    | '/_app/perfil_/cuentas'
    | '/_app/perfil_/datos'
    | '/_app/perfil_/medios-de-pago'
    | '/_app/reservas-transferencia/$id'
    | '/_app/reservas_/$id'
    | '/_app/vehiculos/$id'
    | '/voucher/return/$token'
    | '/voucher/verify/$token'
    | '/_app/mis-vehiculos/$id_/documentos'
    | '/_app/reservas/$id/pago'
    | '/_app/vehiculos/$id_/reservar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecuperarRoute: typeof RecuperarRoute
  RegistroRoute: typeof RegistroRoute
  VerificarRoute: typeof VerificarRoute
  VoucherReturnTokenRoute: typeof VoucherReturnTokenRoute
  VoucherVerifyTokenRoute: typeof VoucherVerifyTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verificar': {
      id: '/verificar'
      path: '/verificar'
      fullPath: '/verificar'
      preLoaderRoute: typeof VerificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/soporte': {
      id: '/_app/soporte'
      path: '/soporte'
      fullPath: '/soporte'
      preLoaderRoute: typeof AppSoporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservas': {
      id: '/_app/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof AppReservasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notificaciones': {
      id: '/_app/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof AppNotificacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mis-vehiculos': {
      id: '/_app/mis-vehiculos'
      path: '/mis-vehiculos'
      fullPath: '/mis-vehiculos'
      preLoaderRoute: typeof AppMisVehiculosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mapa': {
      id: '/_app/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AppMapaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/licencia': {
      id: '/_app/licencia'
      path: '/licencia'
      fullPath: '/licencia'
      preLoaderRoute: typeof AppLicenciaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/identidad': {
      id: '/_app/identidad'
      path: '/identidad'
      fullPath: '/identidad'
      preLoaderRoute: typeof AppIdentidadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favoritos': {
      id: '/_app/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AppFavoritosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracion': {
      id: '/_app/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AppConfiguracionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buscar': {
      id: '/_app/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof AppBuscarRouteImport
      parentRoute: typeof AppRoute
    }
    '/voucher/verify/$token': {
      id: '/voucher/verify/$token'
      path: '/voucher/verify/$token'
      fullPath: '/voucher/verify/$token'
      preLoaderRoute: typeof VoucherVerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voucher/return/$token': {
      id: '/voucher/return/$token'
      path: '/voucher/return/$token'
      fullPath: '/voucher/return/$token'
      preLoaderRoute: typeof VoucherReturnTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vehiculos/$id': {
      id: '/_app/vehiculos/$id'
      path: '/vehiculos/$id'
      fullPath: '/vehiculos/$id'
      preLoaderRoute: typeof AppVehiculosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservas_/$id': {
      id: '/_app/reservas_/$id'
      path: '/reservas/$id'
      fullPath: '/reservas/$id'
      preLoaderRoute: typeof AppReservasIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservas-transferencia/$id': {
      id: '/_app/reservas-transferencia/$id'
      path: '/reservas-transferencia/$id'
      fullPath: '/reservas-transferencia/$id'
      preLoaderRoute: typeof AppReservasTransferenciaIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil_/medios-de-pago': {
      id: '/_app/perfil_/medios-de-pago'
      path: '/perfil/medios-de-pago'
      fullPath: '/perfil/medios-de-pago'
      preLoaderRoute: typeof AppPerfilMediosDePagoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil_/datos': {
      id: '/_app/perfil_/datos'
      path: '/perfil/datos'
      fullPath: '/perfil/datos'
      preLoaderRoute: typeof AppPerfilDatosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil_/cuentas': {
      id: '/_app/perfil_/cuentas'
      path: '/perfil/cuentas'
      fullPath: '/perfil/cuentas'
      preLoaderRoute: typeof AppPerfilCuentasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil_/$id': {
      id: '/_app/perfil_/$id'
      path: '/perfil/$id'
      fullPath: '/perfil/$id'
      preLoaderRoute: typeof AppPerfilIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mis-vehiculos/nuevo': {
      id: '/_app/mis-vehiculos/nuevo'
      path: '/nuevo'
      fullPath: '/mis-vehiculos/nuevo'
      preLoaderRoute: typeof AppMisVehiculosNuevoRouteImport
      parentRoute: typeof AppMisVehiculosRoute
    }
    '/_app/mis-vehiculos/$id': {
      id: '/_app/mis-vehiculos/$id'
      path: '/$id'
      fullPath: '/mis-vehiculos/$id'
      preLoaderRoute: typeof AppMisVehiculosIdRouteImport
      parentRoute: typeof AppMisVehiculosRoute
    }
    '/_app/vehiculos/$id_/reservar': {
      id: '/_app/vehiculos/$id_/reservar'
      path: '/vehiculos/$id/reservar'
      fullPath: '/vehiculos/$id/reservar'
      preLoaderRoute: typeof AppVehiculosIdReservarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservas/$id/pago': {
      id: '/_app/reservas/$id/pago'
      path: '/$id/pago'
      fullPath: '/reservas/$id/pago'
      preLoaderRoute: typeof AppReservasIdPagoRouteImport
      parentRoute: typeof AppReservasRoute
    }
    '/_app/mis-vehiculos/$id_/documentos': {
      id: '/_app/mis-vehiculos/$id_/documentos'
      path: '/$id/documentos'
      fullPath: '/mis-vehiculos/$id/documentos'
      preLoaderRoute: typeof AppMisVehiculosIdDocumentosRouteImport
      parentRoute: typeof AppMisVehiculosRoute
    }
  }
}

interface AppMisVehiculosRouteChildren {
  AppMisVehiculosIdRoute: typeof AppMisVehiculosIdRoute
  AppMisVehiculosNuevoRoute: typeof AppMisVehiculosNuevoRoute
  AppMisVehiculosIdDocumentosRoute: typeof AppMisVehiculosIdDocumentosRoute
}

const AppMisVehiculosRouteChildren: AppMisVehiculosRouteChildren = {
  AppMisVehiculosIdRoute: AppMisVehiculosIdRoute,
  AppMisVehiculosNuevoRoute: AppMisVehiculosNuevoRoute,
  AppMisVehiculosIdDocumentosRoute: AppMisVehiculosIdDocumentosRoute,
}

const AppMisVehiculosRouteWithChildren = AppMisVehiculosRoute._addFileChildren(
  AppMisVehiculosRouteChildren,
)

interface AppReservasRouteChildren {
  AppReservasIdPagoRoute: typeof AppReservasIdPagoRoute
}

const AppReservasRouteChildren: AppReservasRouteChildren = {
  AppReservasIdPagoRoute: AppReservasIdPagoRoute,
}

const AppReservasRouteWithChildren = AppReservasRoute._addFileChildren(
  AppReservasRouteChildren,
)

interface AppRouteChildren {
  AppBuscarRoute: typeof AppBuscarRoute
  AppConfiguracionRoute: typeof AppConfiguracionRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFavoritosRoute: typeof AppFavoritosRoute
  AppIdentidadRoute: typeof AppIdentidadRoute
  AppLicenciaRoute: typeof AppLicenciaRoute
  AppMapaRoute: typeof AppMapaRoute
  AppMisVehiculosRoute: typeof AppMisVehiculosRouteWithChildren
  AppNotificacionesRoute: typeof AppNotificacionesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppReservasRoute: typeof AppReservasRouteWithChildren
  AppSoporteRoute: typeof AppSoporteRoute
  AppPerfilIdRoute: typeof AppPerfilIdRoute
  AppPerfilCuentasRoute: typeof AppPerfilCuentasRoute
  AppPerfilDatosRoute: typeof AppPerfilDatosRoute
  AppPerfilMediosDePagoRoute: typeof AppPerfilMediosDePagoRoute
  AppReservasTransferenciaIdRoute: typeof AppReservasTransferenciaIdRoute
  AppReservasIdRoute: typeof AppReservasIdRoute
  AppVehiculosIdRoute: typeof AppVehiculosIdRoute
  AppVehiculosIdReservarRoute: typeof AppVehiculosIdReservarRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBuscarRoute: AppBuscarRoute,
  AppConfiguracionRoute: AppConfiguracionRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFavoritosRoute: AppFavoritosRoute,
  AppIdentidadRoute: AppIdentidadRoute,
  AppLicenciaRoute: AppLicenciaRoute,
  AppMapaRoute: AppMapaRoute,
  AppMisVehiculosRoute: AppMisVehiculosRouteWithChildren,
  AppNotificacionesRoute: AppNotificacionesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppReservasRoute: AppReservasRouteWithChildren,
  AppSoporteRoute: AppSoporteRoute,
  AppPerfilIdRoute: AppPerfilIdRoute,
  AppPerfilCuentasRoute: AppPerfilCuentasRoute,
  AppPerfilDatosRoute: AppPerfilDatosRoute,
  AppPerfilMediosDePagoRoute: AppPerfilMediosDePagoRoute,
  AppReservasTransferenciaIdRoute: AppReservasTransferenciaIdRoute,
  AppReservasIdRoute: AppReservasIdRoute,
  AppVehiculosIdRoute: AppVehiculosIdRoute,
  AppVehiculosIdReservarRoute: AppVehiculosIdReservarRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RecuperarRoute: RecuperarRoute,
  RegistroRoute: RegistroRoute,
  VerificarRoute: VerificarRoute,
  VoucherReturnTokenRoute: VoucherReturnTokenRoute,
  VoucherVerifyTokenRoute: VoucherVerifyTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
