name: Only allow PRs from dev to main

on:
  pull_request:
    branches:
      - main

jobs:
  check-source-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Validate source branch
        run: |
          echo "Source branch: ${{ github.head_ref }}"

          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "Only PRs from dev to main are allowed."
            exit 1
          fi
